server:
  port: 8081

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        type: TRACE



