INSERT INTO PERSON(FIRSTNAME, SURNAME) VALUES ('Damian', 'Kowalski')
INSERT INTO PERSON(FIRSTNAME, SURNAME) VALUES ('Patryk', 'Rudolf')
INSERT INTO PERSON(FIRSTNAME, SURNAME) VALUES ('Lucjan', 'Moskwa')